#+BEGIN_QUOTE
1. Réalisez un graphique qui vous montrera une oscillation périodique superposée à une évolution systématique plus lente.
2. Séparez ces deux phénomènes. Caractérisez l'oscillation
   périodique. Proposez un modèle simple de la contribution lente,
   estimez ses paramètres et tentez une extrapolation jusqu'à 2025
   (dans le but de pouvoir valider le modèle par des observations
   futures).
#+END_QUOTE

* Présentation des données
  les données proviennent du [[https://scrippsco2.ucsd.edu/data/atmospheric_co2/primary_mlo_co2_record.html][site web de l'institut Scripps]]. Elles ont
    été téléchargées le 24/11/2022 à 09h52 et peuvent être trouvées
    dans le fichier [[file:data/20221124_0952_monthly_in_situ_co2_mlo.csv][données de départ]].
Dans ce fichier, on peut trouver la description suivante:

#+BEGIN_QUOTE
The data file below contains 10 columns.  Columns 1-4 give the dates
    in several redundant formats. Column 5 below gives monthly Mauna
    Loa CO2 concentrations in micro-mol CO2 per mole (ppm), reported
    on the 2012 SIO manometric mole fraction scale.  This is the
    standard version of the data most often sought.  The monthly
    values have been adjusted to 24:00 hours on the 15th of each
    month.  Column 6 gives the same data after a seasonal adjustment
    to remove the quasi-regular seasonal cycle.  The adjustment
    involves subtracting from the data a 4-harmonic fit with a linear
    gain factor.  Column 7 is a smoothed version of the data generated
    from a stiff cubic spline function plus 4-harmonic functions with
    linear gain.  Column 8 is the same smoothed version with the
    seasonal cycle removed.  Column 9 is identical to Column 5 except
    that the missing values from Column 5 have been filled with values
    from Column 7.  Column 10 is identical to Column 6 except missing
    values have been filled with values from Column 8.  Missing values
    are denoted by *-99.99*
#+END_QUOTE

On peut y voir qu'il va falloir faire attention à la présence de
valeurs manquantes, qui seront indiquées par la valeur *-99.99*                                                            



